# Generated by Django 5.2.1 on 2025-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_membershipplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='membership_plans/'),
        ),
    ]
